default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  secure_auth: false
  database: blog4
  username: root
  password: root

development:
  <<: *default
  database: blog4_db

testing:
  <<: *default
  database: blog4_db

production:
  <<: *default
  database: blog4_db
